# Generated by Django 4.2.2 on 2023-06-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('description', models.TextField(verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, verbose_name='slug')),
                ('description', models.CharField(max_length=20, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'периодичность',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, verbose_name='slug')),
                ('description', models.CharField(max_length=20, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'статус',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('subject', models.CharField(max_length=100, verbose_name='тема')),
                ('body', models.TextField(blank=True, null=True, verbose_name='текст сообщения')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.period', verbose_name='периодичность')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.status', verbose_name='статус')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
            },
        ),
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField(verbose_name='начало интервала')),
                ('end', models.TimeField(verbose_name='конец интервала')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.task', verbose_name='задание')),
            ],
            options={
                'verbose_name': 'интервал',
                'verbose_name_plural': 'интервалы',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='время')),
                ('status', models.IntegerField(verbose_name='статус')),
                ('response', models.TextField(verbose_name='ответ сервера')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='клиент')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.task', verbose_name='задание')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tasks',
            field=models.ManyToManyField(to='mailing.task', verbose_name='назначение'),
        ),
    ]
