# Generated by Django 4.2.2 on 2023-06-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_task_period_alter_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
