# Generated by Django 4.2.2 on 2023-06-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_client_options_alter_timewindow_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewindow',
            name='start',
            field=models.TimeField(verbose_name='начало интервала'),
        ),
    ]
