# Generated by Django 4.2.2 on 2023-06-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_timewindow_start'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeWindow',
            new_name='Interval',
        ),
    ]
