# Generated by Django 4.2.2 on 2023-07-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="заголовок")),
                ("content", models.TextField(verbose_name="содержимое")),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="articles"),
                ),
                (
                    "views",
                    models.IntegerField(
                        default=0, verbose_name="количество просмотров"
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата публикации"
                    ),
                ),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
    ]
